version: '3.8'

services:
  short-url-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./short-url-app
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file: .env

  db:
    restart: always
    image: postgres:latest
#    volumes:
#      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

